### PR TITLE
Set RUST_TEST_THREADS=1

### PR DESCRIPTION
**Pull request by rossmuir**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_vault/74)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
good to go

**Comment by dirvine** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- .travis.yml @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_vault/74)

**Pull request merged**
