### PR TITLE
Fixed inconsistent spacing.

### PR DESCRIPTION
**Pull request by a-jamesregan**
The spacing in the functions seem to be inconsistent.  I updated the spacing
between functions to match that found in the rust documentation.

https://doc.rust-lang.org/nightly/book/hello-world.html

According to the rust docs:
>There are a number of details that are important here. The first is that it’s indented with four spaces, not tabs. Please configure your editor of choice to insert four spaces with the tab key.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_vault/147)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @maqi (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by a-jamesregan** [comment]
Is there a Maidsafe contributor guide available somewhere that outlines the code format that is officially used/supported?

**Comment by dirvine** [comment]
No we did have a pretty extensive one for c++ for Rust we will follow the guidelines (as you have posted)

**Comment by maqi** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_vault/147)

**Pull request merged**
