### PR TITLE
expanding vault network test

### PR DESCRIPTION
**Pull request by maqi**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_vault/72)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
At the moment the location of the exe maidsafe_vault is not picked up in CI. I suspect this is due to CI not doing `cargo build` before test. I will reallocate to Ross to confirm. 

---

Review status: all files reviewed, 1 unresolved discussion, some commit checks failed.
Reviewed files:
- src/main.rs @ r1

---

<sup>**[src/main.rs, line 136 \[r1\]](https://reviewable.io:443/reviews/maidsafe/maidsafe_vault/72#-JpwCtVPekcVaZCYoY5M)** ([raw file](https://github.com/maidsafe/maidsafe_vault/blob/e40a1c795d8a11cef226007e780be63af2573b9f/src/main.rs#L136)):</sup>
Very nice, when the swarm issues fix in routing we can probably remove all of these sleeps actually. Well I hope so.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_vault/72)

**Comment by benjaminbollen** [comment]
Nice one Qi, would be great to have the vault exec built and run as part of the CI.  We should then do the same for CRUST and routing example.

**Pull request merged**
