### PR TITLE
Maid-1010 put flow documentation

### PR DESCRIPTION
**Pull request by maqi**
put flow documentation involving Primary, Backup and Sacrificial copies of data

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_vault/81)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
Looks good to me.

**Comment by Viv-Rajkumar** [comment]
Just waiting on @inetic to confirm these are fine before merging this in.

**Comment by inetic** [comment]
I would like to have a link somewhere that explains the language: *->, *->>, {Delete.Sy, So}... Some of it can be guessed, but I would prefer not to.

The doc also seems to suggest that more than one sacrificial copy can be deleted and let upper layers know about. From looking at the code, this is not the case.

**Comment by maqi** [comment]
here is the link for the conventions :
https://github.com/maidsafe-archive/MaidSafe-Vault/blob/next/docs/conventions.md
I will move it into rust code base

regarding the "removal of multiple sacrificial copies", the documentation is aiming for the 'proper' flow,
which may incur some work in next iteration.
The current implementation is limited by the current routing API, so has to be only one copy.

**Comment by inetic** [comment]
Thanks @maqi, looks OK to me then. Sorry for making this longer.

**Pull request merged**
