### PR TITLE
MAID-1010 post flow documentation

### PR DESCRIPTION
**Pull request by maqi**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_vault/84)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
Maybe make it explicit in the documentation that post messages need the signature of the owner of SDV to verify mutation rights.

Looks good to me

**Comment by benjaminbollen** [comment]
So we don't have an explicit post_response in this iteration?

**Comment by ustulation** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- docs/post_flow.md @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_vault/84)

**Pull request merged**
