### PR TITLE
Resolving build failures

### PR DESCRIPTION
**Pull request by ustulation**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_vault/79)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @maqi

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by maidsafe-highfive** [comment]
Windows Build Successful

**Comment by maidsafe-highfive** [comment]
OS X Build Successful

**Comment by Viv-Rajkumar** [comment]
r? dirvine

**Comment by dirvine** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- Cargo.toml @ r2
- src/data_manager/database.rs @ r1
- src/data_manager/mod.rs @ r2
- src/maid_manager/database.rs @ r1
- src/maid_manager/mod.rs @ r2
- src/pmid_manager/database.rs @ r1
- src/pmid_manager/mod.rs @ r1
- src/pmid_node/mod.rs @ r2
- src/vault.rs @ r2
- src/version_handler/mod.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_vault/79)

**Pull request merged**
