### PR TITLE
Maid-1013_resolve_warnings

### PR DESCRIPTION
**Pull request by maqi**
As task MAID-1013 https://maidsafe.atlassian.net/browse/MAID-1013 has been divided into several sub-tasks,
this PR is only trying to resolve the warnings during compilation.
This PR shall not make MAID-1013 to be considered as completed.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_vault/75)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
cargo build and cargo test does not yield any errors or warnings .. So fine.

**Comment by dirvine** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- src/chunk_store/test.rs @ r1
- src/data_manager/database.rs @ r1
- src/maid_manager/mod.rs @ r1
- src/main.rs @ r1
- src/pmid_manager/database.rs @ r1
- src/pmid_node/mod.rs @ r1
- src/vault.rs @ r1
- src/version_handler/mod.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_vault/75)

**Pull request merged**
